# Introduction to Linear Algebra using Numpy

_Author: Zane Lim_

## Learning Objectives

- Introduce linear algebra and how it relates to Data Science
- Define what Numpy is and how it relates to linear algebra
- Vector arrays
- Manipulating arrays- indexing, slicing, arithmetic methods, sorting
- Basic linear algebra

## Lesson Guide

- [What Is Numpy?](#numpy)
- [Ndarray and vectorization](#ndarray)
- [Indexing and slicing](#indexing)
- [Ndarray vector arithmetic and methods](#methods)
- [Sorting and set logic](#sorting)
- [Linear algebra](#linearalgebra)

<a id="numpy"></a>
    
## What is Numpy?

### Linear Algebra

Linear Algebra is the branch that deals with linear equations and linear functions which are represented through matrices and vectors. 

<img src="./assets/linear-algebra.jpg" style="margin: 20px; height: 200px">

It is the theory underpinning most of the Machine Learning and Data Science algorithms.

#### Scalars, Vectors, Matrices and Tensors
- A scalar is a single number
- A vector is an array of numbers.
- A matrix is a 2-D array
- A tensor is a n-dimensional array with n>2

<img src="./assets/tensors.png" style="margin: 20px; height: 200px">

### Numpy 

NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. Most computational packages providing scientific functionality use NumPy’s array objects as the lingua franca for data exchange.

Numpy is designed for efficiency on large arrays of data

-  NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences.
- NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [1]:
import numpy as np

<a id = "ndarray"> </a>

## Ndarray and Vectorization

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

In [2]:
# Generate some random data
data = np.random.randn(2, 3)

data

array([[ 0.09878483,  1.37962744,  1.40080287],
       [-1.16180498,  0.93146587,  1.02337197]])

In [3]:
# mathematical operations (multiplication) on `data`
data * 10

array([[  0.98784826,  13.79627443,  14.00802868],
       [-11.61804978,   9.31465872,  10.2337197 ]])

In [4]:
data + data

array([[ 0.19756965,  2.75925489,  2.80160574],
       [-2.32360996,  1.86293174,  2.04674394]])

In [5]:
# check the size of each dimension
data.shape

(2, 3)

In [6]:
# check the data type of the array
data.dtype

dtype('float64')

In [9]:
# creating new array

# first we have a list
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
# nested list (a list of equal-length lists)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# check the dimensions and shape
print(arr2.ndim)

arr2.shape

2


(2, 4)

In [12]:
# data types are inferred
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
# setting the data types manually
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)    

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
# convert the data type
arr3 = arr2.astype(np.float)

In [19]:
arr3.dtype

dtype('float64')

In [21]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
# comparison between arrays of the same size yields boolean array
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [28]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Indexing and Slicing

In [29]:
# first create a new array using arange (similar to the range function in python)
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

5

In [31]:
arr[5:8]

array([5, 6, 7])

In [42]:
# assigning a scalar value to a slice will broadcast (basically propagate) the value to the entire selection
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
# 2-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2[2]

array([7, 8, 9])

In [46]:
arr2[0][2]

3

In [47]:
arr2[0, 2]

3

Illustration of indexing on a two-dimensional array. It's helpful to think of axis 0 as the “rows” of the array and axis 1 as the “columns.”

<img src="./assets/ndarray.png" style="margin: 20px; height: 300px">

Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

In [48]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# can pass multiple slices
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [50]:
# can combine indexing and slicing such as selecting the second row but only the first two columns
arr2[1, :2]

array([4, 5])

In [51]:
# consider we have some data in an array and an array of names with duplicates.

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
    
data = np.random.randn(7, 4)

In [52]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [54]:
data

array([[ 0.91047179, -0.5448996 ,  0.14054559, -1.63692508],
       [-0.87711255,  1.6237428 ,  1.4434458 ,  0.23735002],
       [-0.24788511,  0.52380514, -1.18924772,  0.47288363],
       [ 1.42091571,  1.22857309, -0.25489433,  0.22650535],
       [ 0.82762875,  0.8690172 ,  1.2933605 ,  0.36962799],
       [ 1.09315521, -1.35597746, -0.87129481, -0.5871499 ],
       [-0.67191891,  1.98898695, -1.16613781,  2.97937322]])

In [55]:
# Suppose each name corresponds to a row in the data array 
# and we wanted to select all the rows with corresponding name 'Bob'.

names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [56]:
data[names == 'Bob']

array([[ 0.91047179, -0.5448996 ,  0.14054559, -1.63692508],
       [ 1.42091571,  1.22857309, -0.25489433,  0.22650535]])

In [57]:
data[names == 'Bob', 2:]

array([[ 0.14054559, -1.63692508],
       [-0.25489433,  0.22650535]])

In [58]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [59]:
# equivalent
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [60]:
data[~(names == 'Bob')]

array([[-0.87711255,  1.6237428 ,  1.4434458 ,  0.23735002],
       [-0.24788511,  0.52380514, -1.18924772,  0.47288363],
       [ 0.82762875,  0.8690172 ,  1.2933605 ,  0.36962799],
       [ 1.09315521, -1.35597746, -0.87129481, -0.5871499 ],
       [-0.67191891,  1.98898695, -1.16613781,  2.97937322]])

In [61]:
# combine multiple boolean conditions
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [62]:
data[mask]

array([[ 0.91047179, -0.5448996 ,  0.14054559, -1.63692508],
       [-0.24788511,  0.52380514, -1.18924772,  0.47288363],
       [ 1.42091571,  1.22857309, -0.25489433,  0.22650535],
       [ 0.82762875,  0.8690172 ,  1.2933605 ,  0.36962799]])

In [63]:
# setting values using boolean array
data[data < 0] = 0

data

array([[0.91047179, 0.        , 0.14054559, 0.        ],
       [0.        , 1.6237428 , 1.4434458 , 0.23735002],
       [0.        , 0.52380514, 0.        , 0.47288363],
       [1.42091571, 1.22857309, 0.        , 0.22650535],
       [0.82762875, 0.8690172 , 1.2933605 , 0.36962799],
       [1.09315521, 0.        , 0.        , 0.        ],
       [0.        , 1.98898695, 0.        , 2.97937322]])

<a id = "methods"> </a>

## Ndarray vector arithmetic and methods

In [64]:
# create a new array
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
# reshaping the array
arr = arr.reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
# transpose
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [67]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [68]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [72]:
arr = np.random.randn(7)
arr

array([ 0.71575733, -1.11322125,  1.84409887, -0.64102877,  1.42768209,
       -0.26429019,  0.65217762])

In [73]:
# nan: not a number
np.sqrt(arr)

/Users/zane/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.84602443,        nan, 1.35797602,        nan, 1.19485651,
              nan, 0.80757515])

In [74]:
arr.max()

1.8440988719116682

In [75]:
arr.mean()

0.37445367205313407

<a id = "sorting"> </a>

## Sorting and Set Logic

In [76]:
arr = np.random.randn(6)
arr

array([-1.030699  , -0.80476228,  0.03334791,  0.74695389, -2.21815931,
        0.18052398])

In [77]:
# sorting is inplace
arr.sort()

In [78]:
arr

array([-2.21815931, -1.030699  , -0.80476228,  0.03334791,  0.18052398,
        0.74695389])

In [79]:
arr = np.random.randn(5, 3)
arr

array([[ 0.33917401, -0.57040966,  0.48030255],
       [ 0.6899113 , -0.52424832, -0.45852145],
       [-0.81602892,  0.84454054, -1.95987245],
       [-0.19792505, -1.41457269,  0.23040223],
       [ 0.78881004, -0.31577452,  2.14901201]])

In [80]:
# sorting along columns
arr.sort(1)

In [81]:
arr

array([[-0.57040966,  0.33917401,  0.48030255],
       [-0.52424832, -0.45852145,  0.6899113 ],
       [-1.95987245, -0.81602892,  0.84454054],
       [-1.41457269, -0.19792505,  0.23040223],
       [-0.31577452,  0.78881004,  2.14901201]])

In [86]:
names1 = np.array(['Melissa', 'Vernie', 'Hafi', 'Krut', 'Vernie', 'Melissa', 'Hafi'])

In [87]:
np.unique(names1)

array(['Hafi', 'Krut', 'Melissa', 'Vernie'], dtype='<U7')

In [89]:
names2 = np.array(['Hami', 'Ryan', 'Cathy', 'Vernie', 'Krut'])

In [90]:
np.in1d(names1, names2)

array([False,  True, False,  True,  True, False, False])

In [91]:
np.intersect1d(names1, names2)

array(['Krut', 'Vernie'], dtype='<U7')

In [92]:
np.union1d(names1, names2)

array(['Cathy', 'Hafi', 'Hami', 'Krut', 'Melissa', 'Ryan', 'Vernie'],
      dtype='<U7')

<a id = "linearalgebra"> </a>

## Linear Algebra

In [94]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [96]:
x.shape

(2, 3)

In [95]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [97]:
y.shape

(3, 2)

In [98]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [99]:
# equivalent
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [100]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [101]:
# equivalent
x @ np.ones(3)

array([ 6., 15.])